import { Metadata } from "next";

import "./globals.css";
import { cormorant } from "@/_lib/font";
import TransitionProvider from "@/components/TransitionProvider";

export const metadata: Metadata = {
	title: "Uday's Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={`
		${cormorant.className} 
		bg-gradient-to-br from-secondary/30 to-primary/25 
		text-text antialiased 
		min-h-screen flex flex-col 
		mx-auto max-w-screen-xl px-4 sm:px-6 md:px-8
	`}
			>
				<TransitionProvider>{children}</TransitionProvider>
			</body>
		</html>
	);
}
